### ISSUE TITLE
JUST A IDEA: Player Heads as Blocks

### ISSUE THREAD

**Issue by TheWalkingDrift** [Enes5519/PlayerHead#17]

**Comment by TheWalkingDrift** [comment]
And do you have Discord ?

**Comment by Enes5519** [comment]
This is not possible for now but I can show entity as a block.

**Comment by TheWalkingDrift** [comment]
Is's possible !

https://youtu.be/gzFseUcvEt0

**Comment by TheWalkingDrift** [comment]
But in this Video he can place Playerheads and they are Blocks

https://youtu.be/gzFseUcvEt0

**Comment by Enes5519** [comment]
I think there's a skull under the entity. But I'm not sure, I just thought of it.

**Comment by TheWalkingDrift** [comment]
Yes, there is a Skull in the Server entengames.net is it Like there and when it lags there is a normal Head for a moment

**Comment by TheWalkingDrift** [comment]
And can you make a Version for API 3.9

**Comment by Enes5519** [comment]
I have not PC so I can't update.

Edit: My phone is 32bit.

**Comment by TheWalkingDrift** [comment]
Why ?

**Comment by TheWalkingDrift** [comment]
Oh the edit

**Comment by TheWalkingDrift** [comment]
And how did you Code the Plugin ?

**Comment by Enes5519** [comment]
At that time I had a vds, but now I don't

**Comment by TheWalkingDrift** [comment]
When can you Update it ?

**Comment by TheWalkingDrift** [comment]
And how do you updated AnywhereBackpacj

**Comment by Enes5519** [comment]
What is `AnywhereBackpack`?

**Comment by TheWalkingDrift** [comment]
Oh sry false Developer

**Comment by Wertzui123** [comment]
Yea, SalmonDE places a skull block under the entity and I think this would be epic to implement in this plugin. On the other hand, not everything cool should be public so if you are able to, nice, but if not, it will still be something special (;

**Comment by MesterJeff** [comment]
H

**Comment by TheWalkingDrift** [comment]
.
