### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IonicSyz1823** [Enes5519/PlayerHead#8]
03.03 01:13:13 [Server] Server thread/CRITICAL Error: "Class 'pocketmine\entity\EntityFactory' not found" (EXCEPTION) in "plugins/PlayerHead_dev-13 (1).phar/src/Enes5519/PlayerHead/PlayerHead" at line 54
03.03 01:13:13 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/PluginBase(123): Enes5519\PlayerHead\PlayerHead->onEnable()
03.03 01:13:13 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PluginManager(587): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
03.03 01:13:13 [Server] Server thread/DEBUG #2 src/pocketmine/Server(2003): pocketmine\plugin\PluginManager->enablePlugin(Enes5519\PlayerHead\PlayerHead object)
03.03 01:13:13 [Server] Server thread/DEBUG #3 src/pocketmine/Server(1989): pocketmine\Server->enablePlugin(Enes5519\PlayerHead\PlayerHead object)
03.03 01:13:13 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1783): pocketmine\Server->enablePlugins(integer 1)
03.03 01:13:13 [Server] Server thread/DEBUG #5 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
03.03 01:13:13 [Server] Server thread/DEBUG #6 (1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
03.03 01:13:13 [Server] Server thread/INFO Disabling PlayerHead v1.2

**Comment by Enes5519** [comment]
You're not using `PocketMine-MP 4.0.0`.
